apiVersion: apps/v1
kind: Deployment

metadata:
  name: calculator
  namespace: calculator

spec:
  replicas: 2

  selector:
    matchLabels:
      app: calculator

  template:
    metadata:
      labels:
        app: calculator

    spec:
      containers:
        - name: calculator
          image: pp0104/calculator-docker-lab:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8080

          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi