apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml

replicas:
  - name: calculator
    count: 2

images:
  - name: pp0104/calculator-docker-lab
    newTag: jenkins-19